// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXz1C2PRr1Ec5yKTgIJyCIjXrb9XMy1KM',
    appId: '1:81704932385:web:8cc8befb1b60028fb3bf60',
    messagingSenderId: '81704932385',
    projectId: 'waterapptest-da0bf',
    authDomain: 'waterapptest-da0bf.firebaseapp.com',
    storageBucket: 'waterapptest-da0bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC80PbWXMtfPTf4KZM4mF-l5RWLbueJmOo',
    appId: '1:81704932385:android:06214e16f473dd9db3bf60',
    messagingSenderId: '81704932385',
    projectId: 'waterapptest-da0bf',
    storageBucket: 'waterapptest-da0bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfV8qOO-5IETZd2W2ZuFxxK7krnQfYHSs',
    appId: '1:81704932385:ios:a787515fb653c229b3bf60',
    messagingSenderId: '81704932385',
    projectId: 'waterapptest-da0bf',
    storageBucket: 'waterapptest-da0bf.appspot.com',
    iosClientId: '81704932385-lt3cvsobnsfac2v78ookp42iotp7ffjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.watintake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfV8qOO-5IETZd2W2ZuFxxK7krnQfYHSs',
    appId: '1:81704932385:ios:a787515fb653c229b3bf60',
    messagingSenderId: '81704932385',
    projectId: 'waterapptest-da0bf',
    storageBucket: 'waterapptest-da0bf.appspot.com',
    iosClientId: '81704932385-lt3cvsobnsfac2v78ookp42iotp7ffjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.watintake',
  );
}
